In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv("/Users/kushal/Downloads/thyroid0387.data",header=None, low_memory=False)
df.head()

In [4]:
df.dtypes

0      int64
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
21    object
22    object
23    object
24    object
25    object
26    object
27    object
28    object
29    object
dtype: object

In [5]:
df.shape

(9172, 30)

In [6]:
X = df.drop([5,29,28,17,19,23,25,27],axis=1) #this is predictor variable x

In [7]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           dtype='int64')

In [8]:
X.columns

Int64Index([0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 21,
            22, 24, 26],
           dtype='int64')

In [9]:
X.head(6)

   0  1  2  3  4  6  7  8  9  10  ... 13 14 15 16 18 20   21 22 24 26
0  29  F  f  f  f  f  f  f  t  f  ...  f  f  f  t  f  f    ?  f  f  f
1  29  F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  128  f  f  f
2  41  F  f  f  f  f  f  f  f  t  ...  f  f  f  f  f  f    ?  f  f  t
3  36  F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f    ?  f  f  t
4  32  F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f    ?  f  f  t
5  60  F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f    ?  f  f  t

[6 rows x 22 columns]

In [10]:
X=='?'

/Users/kushal/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

,0,1,2,3,4,6,7,8,9,10,...,13,14,15,16,18,20,21,22,24,26
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9142,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9143,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9144,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9145,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9146,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9147,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9148,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
9149,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9150,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9151,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9152,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9153,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9154,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9155,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9156,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9157,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9158,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9159,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9160,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9161,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9162,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9163,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9164,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9165,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9166,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9167,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9168,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9169,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9170,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9171,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
X_new=X.replace('?',np.nan)
X_new

      0    1  2  3  4  6  7  8  9  10  ... 13 14 15 16 18 20   21 22 24 26
0     29    F  f  f  f  f  f  f  t  f  ...  f  f  f  t  f  f  NaN  f  f  f
1     29    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  128  f  f  f
2     41    F  f  f  f  f  f  f  f  t  ...  f  f  f  f  f  f  NaN  f  f  t
3     36    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f  NaN  f  f  t
4     32    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f  NaN  f  f  t
5     60    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f  NaN  f  f  t
6     77    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f  NaN  f  f  t
7     28    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  116  f  f  f
8     28    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t   76  f  f  f
9     28    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t   83  f  f  f
10    54    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  133  f  f  f
11    42    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  105  f  f  f
12    51    M  t  f  f  f  f  f  f  f  ...  f  f  f  t  f  f  NaN  f  f  f
13    51    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  116  f  f  f
14    37    F  f  f  f  f  f  f  f  f  ...  t  f  f  f  t  f  NaN  f  f  f
15    16    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  f  NaN  f  f  f
16    54    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  122  f  f  f
17    43    M  f  f  f  f  f  f  f  f  ...  f  f  f  f  t  t  116  f  f  f
18    63    F  t  f  f  f  f  f  f  f  ...  f  f  f  t  f  t   48  t  t  f
19    36    F  f  f  f  f  f  f  t  t  ...  f  f  f  t  t  t   90  t  t  f
20    40    F  f  t  f  f  f  f  f  f  ...  f  f  f  f  f  t   79  t  t  f
21    40    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  104  t  t  f
22    40    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t   88  t  t  f
23    77    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  107  t  t  f
24    77  NaN  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  126  f  f  f
25    77    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  113  t  t  f
26    77    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  150  f  f  f
27    51    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t   93  t  t  f
28    75    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t  157  t  t  f
29    56    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  t  t   80  t  t  f
...   ..  ... .. .. .. .. .. .. .. ..  ... .. .. .. .. .. ..  ... .. .. ..
9142  15    F  f  f  f  f  f  f  f  t  ...  f  f  f  t  f  t   92  t  t  f
9143  48    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  104  t  t  f
9144  63    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t   62  t  t  f
9145  80    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t   94  t  t  f
9146  40    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  113  t  t  f
9147  16    M  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t  124  t  t  f
9148  35    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  f  NaN  f  f  f
9149  75    F  t  f  f  f  f  f  t  f  ...  f  f  f  t  f  t   54  t  t  f
9150  62    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t   81  t  t  f
9151  84    F  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  105  t  t  f
9152  80    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  111  t  t  f
9153  64    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t   31  t  t  f
9154  16    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  122  t  t  f
9155  54    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t  105  t  t  f
9156  78    M  f  f  f  f  f  f  f  f  ...  f  f  f  t  f  t   97  t  t  f
9157  60    M  f  f  t  f  f  f  f  f  ...  f  f  f  t  f  t   28  t  t  f
9158  64    M  f  f  f  f  f  f  t  f  ...  f  f  f  f  f  t   44  t  t  f
9159  72    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t  125  t  t  f
9160  72    F  f  f  f  f  f  f  f  t  ...  f  f  f  f  f  t   93  t  t  f
9161  46    F  f  f  f  f  f  f  f  f  ...  f  f  t  f  f  t   70  t  t  f
9162  36    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t   84  t  t  f
9163  69    F  t  f  f  f  f  f  f  f  ...  t  f  f  f  f  t   94  t  t  f
9164  40    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t   67  t  t  f
9165  33    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t   76  t  t  f
9166  70    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t   88  t  t  f
9167  56    M  f  f  f  f  f  f  f  t  ...  f  f  f  f  f  t   64  t  t  f
9168  22    M  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t   91  t  t  f
9169  69    M  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t  113  t  t  f
9170  47    F  f  f  f  f  f  f  f  f  ...  f  f  f  f  f  t   75  t  t  f
9171  31    M  f  f  f  f  f  f  t  f  ...  f  f  f  f  f  t   66  t  t  f

[9172 rows x 22 columns]

In [12]:
X_new.shape

(9172, 22)

In [13]:
X_new.isna().sum()

0       0
1     307
2       0
3       0
4       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
18      0
20      0
21    442
22      0
24      0
26      0
dtype: int64

In [14]:
X_new.shape

(9172, 22)

In [15]:
X_new2= X_new.dropna()

In [16]:
X_new2.shape

(8445, 22)

In [17]:
X_new2.isna().sum()

0     0
1     0
2     0
3     0
4     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
18    0
20    0
21    0
22    0
24    0
26    0
dtype: int64

In [18]:
X_new2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8445 entries, 1 to 9171
Data columns (total 22 columns):
0     8445 non-null int64
1     8445 non-null object
2     8445 non-null object
3     8445 non-null object
4     8445 non-null object
6     8445 non-null object
7     8445 non-null object
8     8445 non-null object
9     8445 non-null object
10    8445 non-null object
11    8445 non-null object
12    8445 non-null object
13    8445 non-null object
14    8445 non-null object
15    8445 non-null object
16    8445 non-null object
18    8445 non-null object
20    8445 non-null object
21    8445 non-null object
22    8445 non-null object
24    8445 non-null object
26    8445 non-null object
dtypes: int64(1), object(21)
memory usage: 1.5+ MB

In [19]:
sick=df.iloc[:,5] #this is y that is response variable

In [20]:
sick.shape

(9172,)

In [21]:
X_new2.columns = X_new2.columns.astype("str")

In [22]:
X_new3 =X_new2.rename(columns={"0":"AGE","1":"SEX","2":"ON THYROXINE","3":"QUERY ON THYROXINE",
                              "4":"ON ANTITHYROID MEDICATION","6":"PREGNENT","7":"THYROID SURGERY",
                              "8":"I131 TREATMENT","9": "QUERY HYPOTHYROID","10":"QUERY HYPERTHYROID",
                              "11":"LITHIUM","12":"GOITRE","13":"TUMOR","14":"HYPOPITUITARY","15":"PSYCH",
                              "16":"TSH MEASURED","18":"T3 MEASURED","20":"TT4 MEASURED","21":"TT4",
                              "22":"T4U","24":"FTI MEASURED","26":"TBG MEASURED"})

In [23]:
X_new3.columns

Index(['AGE', 'SEX', 'ON THYROXINE', 'QUERY ON THYROXINE',
       'ON ANTITHYROID MEDICATION', 'PREGNENT', 'THYROID SURGERY',
       'I131 TREATMENT', 'QUERY HYPOTHYROID', 'QUERY HYPERTHYROID', 'LITHIUM',
       'GOITRE', 'TUMOR', 'HYPOPITUITARY', 'PSYCH', 'TSH MEASURED',
       'T3 MEASURED', 'TT4 MEASURED', 'TT4', 'T4U', 'FTI MEASURED',
       'TBG MEASURED'],
      dtype='object')

In [24]:
X_new3['TT4'] = pd.to_numeric(X_new3['TT4'])

In [25]:
X_new3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8445 entries, 1 to 9171
Data columns (total 22 columns):
AGE                          8445 non-null int64
SEX                          8445 non-null object
ON THYROXINE                 8445 non-null object
QUERY ON THYROXINE           8445 non-null object
ON ANTITHYROID MEDICATION    8445 non-null object
PREGNENT                     8445 non-null object
THYROID SURGERY              8445 non-null object
I131 TREATMENT               8445 non-null object
QUERY HYPOTHYROID            8445 non-null object
QUERY HYPERTHYROID           8445 non-null object
LITHIUM                      8445 non-null object
GOITRE                       8445 non-null object
TUMOR                        8445 non-null object
HYPOPITUITARY                8445 non-null object
PSYCH                        8445 non-null object
TSH MEASURED                 8445 non-null object
T3 MEASURED                  8445 non-null object
TT4 MEASURED                 8445 non-null object
TT4                          8445 non-null float64
T4U                          8445 non-null object
FTI MEASURED                 8445 non-null object
TBG MEASURED                 8445 non-null object
dtypes: float64(1), int64(1), object(20)
memory usage: 1.5+ MB

In [26]:
sick

0       f
1       f
2       f
3       f
4       f
5       f
6       f
7       f
8       f
9       f
10      f
11      f
12      f
13      f
14      f
15      f
16      f
17      f
18      t
19      f
20      f
21      f
22      f
23      f
24      f
25      f
26      f
27      f
28      f
29      f
       ..
9142    f
9143    f
9144    f
9145    f
9146    f
9147    f
9148    f
9149    f
9150    f
9151    f
9152    f
9153    f
9154    f
9155    f
9156    f
9157    f
9158    f
9159    f
9160    f
9161    f
9162    f
9163    f
9164    f
9165    f
9166    f
9167    f
9168    f
9169    f
9170    f
9171    f
Name: 5, Length: 9172, dtype: object

In [27]:
X_new4= pd.get_dummies(X_new3)

In [28]:
X_new4.columns

Index(['AGE', 'TT4', 'SEX_F', 'SEX_M', 'ON THYROXINE_f', 'ON THYROXINE_t',
       'QUERY ON THYROXINE_f', 'QUERY ON THYROXINE_t',
       'ON ANTITHYROID MEDICATION_f', 'ON ANTITHYROID MEDICATION_t',
       'PREGNENT_f', 'PREGNENT_t', 'THYROID SURGERY_f', 'THYROID SURGERY_t',
       'I131 TREATMENT_f', 'I131 TREATMENT_t', 'QUERY HYPOTHYROID_f',
       'QUERY HYPOTHYROID_t', 'QUERY HYPERTHYROID_f', 'QUERY HYPERTHYROID_t',
       'LITHIUM_f', 'LITHIUM_t', 'GOITRE_f', 'GOITRE_t', 'TUMOR_f', 'TUMOR_t',
       'HYPOPITUITARY_f', 'HYPOPITUITARY_t', 'PSYCH_f', 'PSYCH_t',
       'TSH MEASURED_f', 'TSH MEASURED_t', 'T3 MEASURED_f', 'T3 MEASURED_t',
       'TT4 MEASURED_t', 'T4U_f', 'T4U_t', 'FTI MEASURED_f', 'FTI MEASURED_t',
       'TBG MEASURED_f', 'TBG MEASURED_t'],
      dtype='object')

In [29]:
X_new4.head()

,AGE,TT4,SEX_F,SEX_M,ON THYROXINE_f,ON THYROXINE_t,QUERY ON THYROXINE_f,QUERY ON THYROXINE_t,ON ANTITHYROID MEDICATION_f,ON ANTITHYROID MEDICATION_t,...,TSH MEASURED_t,T3 MEASURED_f,T3 MEASURED_t,TT4 MEASURED_t,T4U_f,T4U_t,FTI MEASURED_f,FTI MEASURED_t,TBG MEASURED_f,TBG MEASURED_t
1,29,128.0,1,0,1,0,1,0,1,0,...,1,0,1,1,1,0,1,0,1,0
7,28,116.0,1,0,1,0,1,0,1,0,...,1,0,1,1,1,0,1,0,1,0
8,28,76.0,1,0,1,0,1,0,1,0,...,1,0,1,1,1,0,1,0,1,0
9,28,83.0,1,0,1,0,1,0,1,0,...,1,0,1,1,1,0,1,0,1,0
10,54,133.0,1,0,1,0,1,0,1,0,...,1,0,1,1,1,0,1,0,1,0

In [30]:
X_new4['sick'] = sick

In [31]:
X_new4.head()

,AGE,TT4,SEX_F,SEX_M,ON THYROXINE_f,ON THYROXINE_t,QUERY ON THYROXINE_f,QUERY ON THYROXINE_t,ON ANTITHYROID MEDICATION_f,ON ANTITHYROID MEDICATION_t,...,T3 MEASURED_f,T3 MEASURED_t,TT4 MEASURED_t,T4U_f,T4U_t,FTI MEASURED_f,FTI MEASURED_t,TBG MEASURED_f,TBG MEASURED_t,sick
1,29,128.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,f
7,28,116.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,f
8,28,76.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,f
9,28,83.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,f
10,54,133.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,f

In [32]:
def convert(x):
    if x == 'f':
        return 0
    elif x == 't':
        return 1
X_new4['sick_new']= X_new4['sick'].apply(lambda x : convert(x))

In [33]:
X_new4['sick_new'].unique()

array([0, 1])

In [34]:
X_new4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8445 entries, 1 to 9171
Data columns (total 43 columns):
AGE                            8445 non-null int64
TT4                            8445 non-null float64
SEX_F                          8445 non-null uint8
SEX_M                          8445 non-null uint8
ON THYROXINE_f                 8445 non-null uint8
ON THYROXINE_t                 8445 non-null uint8
QUERY ON THYROXINE_f           8445 non-null uint8
QUERY ON THYROXINE_t           8445 non-null uint8
ON ANTITHYROID MEDICATION_f    8445 non-null uint8
ON ANTITHYROID MEDICATION_t    8445 non-null uint8
PREGNENT_f                     8445 non-null uint8
PREGNENT_t                     8445 non-null uint8
THYROID SURGERY_f              8445 non-null uint8
THYROID SURGERY_t              8445 non-null uint8
I131 TREATMENT_f               8445 non-null uint8
I131 TREATMENT_t               8445 non-null uint8
QUERY HYPOTHYROID_f            8445 non-null uint8
QUERY HYPOTHYROID_t            8445 non-null uint8
QUERY HYPERTHYROID_f           8445 non-null uint8
QUERY HYPERTHYROID_t           8445 non-null uint8
LITHIUM_f                      8445 non-null uint8
LITHIUM_t                      8445 non-null uint8
GOITRE_f                       8445 non-null uint8
GOITRE_t                       8445 non-null uint8
TUMOR_f                        8445 non-null uint8
TUMOR_t                        8445 non-null uint8
HYPOPITUITARY_f                8445 non-null uint8
HYPOPITUITARY_t                8445 non-null uint8
PSYCH_f                        8445 non-null uint8
PSYCH_t                        8445 non-null uint8
TSH MEASURED_f                 8445 non-null uint8
TSH MEASURED_t                 8445 non-null uint8
T3 MEASURED_f                  8445 non-null uint8
T3 MEASURED_t                  8445 non-null uint8
TT4 MEASURED_t                 8445 non-null uint8
T4U_f                          8445 non-null uint8
T4U_t                          8445 non-null uint8
FTI MEASURED_f                 8445 non-null uint8
FTI MEASURED_t                 8445 non-null uint8
TBG MEASURED_f                 8445 non-null uint8
TBG MEASURED_t                 8445 non-null uint8
sick                           8445 non-null object
sick_new                       8445 non-null int64
dtypes: float64(1), int64(2), object(1), uint8(39)
memory usage: 651.5+ KB

In [35]:
X_new5= X_new4.drop('sick',axis=1)

In [36]:
X_new5.head()

,AGE,TT4,SEX_F,SEX_M,ON THYROXINE_f,ON THYROXINE_t,QUERY ON THYROXINE_f,QUERY ON THYROXINE_t,ON ANTITHYROID MEDICATION_f,ON ANTITHYROID MEDICATION_t,...,T3 MEASURED_f,T3 MEASURED_t,TT4 MEASURED_t,T4U_f,T4U_t,FTI MEASURED_f,FTI MEASURED_t,TBG MEASURED_f,TBG MEASURED_t,sick_new
1,29,128.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,0
7,28,116.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,0
8,28,76.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,0
9,28,83.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,0
10,54,133.0,1,0,1,0,1,0,1,0,...,0,1,1,1,0,1,0,1,0,0

In [37]:
df_thyroid_preds= X_new5[['AGE','TT4','SEX_F','SEX_M','ON THYROXINE_f','ON THYROXINE_t','T3 MEASURED_f','T3 MEASURED_t','FTI MEASURED_f',
                     'FTI MEASURED_t','sick_new']]

In [38]:
df_thyroid_preds.head()

,AGE,TT4,SEX_F,SEX_M,ON THYROXINE_f,ON THYROXINE_t,T3 MEASURED_f,T3 MEASURED_t,FTI MEASURED_f,FTI MEASURED_t,sick_new
1,29,128.0,1,0,1,0,0,1,1,0,0
7,28,116.0,1,0,1,0,0,1,1,0,0
8,28,76.0,1,0,1,0,0,1,1,0,0
9,28,83.0,1,0,1,0,0,1,1,0,0
10,54,133.0,1,0,1,0,0,1,1,0,0

In [39]:
X = df_thyroid_preds.drop('sick_new', axis =1)

In [40]:
y = df_thyroid_preds['sick_new']

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2,random_state= 101)

In [43]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6756, 10), (1689, 10), (6756,), (1689,))

## DECISION TREE

In [44]:
from sklearn.tree import DecisionTreeClassifier

In [45]:
dtree = DecisionTreeClassifier()

In [46]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [47]:
 prediction= dtree.predict(X_test)

In [48]:
df_thyroid_preds_new_dt = pd.DataFrame({'Actual': y_test, 'Predicted': prediction})

In [49]:
df_thyroid_preds_new_dt

      Actual  Predicted
8653       1          0
8429       0          0
785        0          0
1324       0          0
7712       0          0
1672       0          0
2534       0          0
5380       0          0
4945       0          0
521        0          0
1104       0          0
5817       0          0
8710       0          0
7146       0          1
1752       0          0
2410       0          0
8433       0          0
3775       0          0
4363       0          0
2649       0          0
2204       0          0
3298       0          0
8521       0          0
9048       0          0
635        0          0
4405       0          0
5266       0          0
3913       0          0
6074       0          0
7030       0          0
...      ...        ...
191        0          0
8486       0          0
436        0          0
6249       0          0
3230       0          0
2873       0          0
4275       0          0
3531       0          0
1284       0          0
4600       0          0
489        0          0
5412       0          0
835        0          1
5654       0          0
1597       0          0
1252       0          0
6510       0          0
7783       0          0
1886       0          0
5484       0          0
135        0          0
6735       0          0
7995       0          0
8878       1          0
8499       0          0
4583       0          0
8824       1          0
8687       0          0
7328       0          0
8693       0          0

[1689 rows x 2 columns]

In [50]:
from sklearn import metrics

In [51]:
print("Accuracy:",metrics.accuracy_score(y_test, prediction))

Accuracy: 0.9253996447602132

## RANDOM FOREST

In [52]:
from sklearn .ensemble import RandomForestClassifier

In [53]:
rfc = RandomForestClassifier(n_estimators=200)

In [54]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [55]:
rfc_pred = rfc.predict(X_test)

In [56]:
df_thyroid_preds_new_rf = pd.DataFrame({'Actual': y_test, 'Predicted_rf': rfc_pred})

In [57]:
df_thyroid_preds_new_rf

      Actual  Predicted_rf
8653       1             0
8429       0             0
785        0             0
1324       0             0
7712       0             0
1672       0             0
2534       0             0
5380       0             0
4945       0             0
521        0             0
1104       0             0
5817       0             0
8710       0             0
7146       0             0
1752       0             0
2410       0             0
8433       0             0
3775       0             0
4363       0             0
2649       0             0
2204       0             0
3298       0             0
8521       0             0
9048       0             0
635        0             0
4405       0             0
5266       0             0
3913       0             0
6074       0             0
7030       0             0
...      ...           ...
191        0             0
8486       0             0
436        0             0
6249       0             0
3230       0             0
2873       0             0
4275       0             0
3531       0             0
1284       0             0
4600       0             0
489        0             0
5412       0             0
835        0             0
5654       0             0
1597       0             0
1252       0             0
6510       0             0
7783       0             0
1886       0             0
5484       0             0
135        0             0
6735       0             0
7995       0             0
8878       1             0
8499       0             0
4583       0             0
8824       1             0
8687       0             0
7328       0             0
8693       0             0

[1689 rows x 2 columns]

In [58]:
print("Accuracy:",metrics.accuracy_score(y_test, rfc_pred))

Accuracy: 0.9502664298401421

## LOGISTIC REGRESSION

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
l_reg = LogisticRegression()
l_reg.fit(X_train,y_train)

/Users/kushal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [61]:
y_pred = l_reg.predict(X_test)

In [62]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [63]:
metrics.accuracy_score(y_test,y_pred)

0.9591474245115453

## SVC